// Generated by gencpp from file yarp_ros_interfaces/Yarpinfo.msg
// DO NOT EDIT!


#ifndef YARP_ROS_INTERFACES_MESSAGE_YARPINFO_H
#define YARP_ROS_INTERFACES_MESSAGE_YARPINFO_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace yarp_ros_interfaces
{
template <class ContainerAllocator>
struct Yarpinfo_
{
  typedef Yarpinfo_<ContainerAllocator> Type;

  Yarpinfo_()
    : Header()
    , msg()  {
    }
  Yarpinfo_(const ContainerAllocator& _alloc)
    : Header(_alloc)
    , msg(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _Header_type;
  _Header_type Header;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _msg_type;
  _msg_type msg;





  typedef boost::shared_ptr< ::yarp_ros_interfaces::Yarpinfo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::yarp_ros_interfaces::Yarpinfo_<ContainerAllocator> const> ConstPtr;

}; // struct Yarpinfo_

typedef ::yarp_ros_interfaces::Yarpinfo_<std::allocator<void> > Yarpinfo;

typedef boost::shared_ptr< ::yarp_ros_interfaces::Yarpinfo > YarpinfoPtr;
typedef boost::shared_ptr< ::yarp_ros_interfaces::Yarpinfo const> YarpinfoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::yarp_ros_interfaces::Yarpinfo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::yarp_ros_interfaces::Yarpinfo_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::yarp_ros_interfaces::Yarpinfo_<ContainerAllocator1> & lhs, const ::yarp_ros_interfaces::Yarpinfo_<ContainerAllocator2> & rhs)
{
  return lhs.Header == rhs.Header &&
    lhs.msg == rhs.msg;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::yarp_ros_interfaces::Yarpinfo_<ContainerAllocator1> & lhs, const ::yarp_ros_interfaces::Yarpinfo_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace yarp_ros_interfaces

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::yarp_ros_interfaces::Yarpinfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::yarp_ros_interfaces::Yarpinfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yarp_ros_interfaces::Yarpinfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yarp_ros_interfaces::Yarpinfo_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yarp_ros_interfaces::Yarpinfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yarp_ros_interfaces::Yarpinfo_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::yarp_ros_interfaces::Yarpinfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9e598282f81ec5c52bf15386d41b34bb";
  }

  static const char* value(const ::yarp_ros_interfaces::Yarpinfo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9e598282f81ec5c5ULL;
  static const uint64_t static_value2 = 0x2bf15386d41b34bbULL;
};

template<class ContainerAllocator>
struct DataType< ::yarp_ros_interfaces::Yarpinfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "yarp_ros_interfaces/Yarpinfo";
  }

  static const char* value(const ::yarp_ros_interfaces::Yarpinfo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::yarp_ros_interfaces::Yarpinfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header Header\n"
"string msg\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::yarp_ros_interfaces::Yarpinfo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::yarp_ros_interfaces::Yarpinfo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Header);
      stream.next(m.msg);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Yarpinfo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::yarp_ros_interfaces::Yarpinfo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::yarp_ros_interfaces::Yarpinfo_<ContainerAllocator>& v)
  {
    s << indent << "Header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.Header);
    s << indent << "msg: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.msg);
  }
};

} // namespace message_operations
} // namespace ros

#endif // YARP_ROS_INTERFACES_MESSAGE_YARPINFO_H
