set(_CATKIN_CURRENT_PACKAGE "yarp_ros_proxy")
set(yarp_ros_proxy_VERSION "0.0.0")
set(yarp_ros_proxy_MAINTAINER "jbarmagen <jbarmagen@todo.todo>")
set(yarp_ros_proxy_PACKAGE_FORMAT "2")
set(yarp_ros_proxy_BUILD_DEPENDS "roscpp" "std_msgs" "yarp_ros_interfaces")
set(yarp_ros_proxy_BUILD_EXPORT_DEPENDS "roscpp" "std_msgs" "yarp_ros_interfaces")
set(yarp_ros_proxy_BUILDTOOL_DEPENDS "catkin")
set(yarp_ros_proxy_BUILDTOOL_EXPORT_DEPENDS )
set(yarp_ros_proxy_EXEC_DEPENDS "roscpp" "std_msgs" "yarp_ros_interfaces")
set(yarp_ros_proxy_RUN_DEPENDS "roscpp" "std_msgs" "yarp_ros_interfaces")
set(yarp_ros_proxy_TEST_DEPENDS )
set(yarp_ros_proxy_DOC_DEPENDS )
set(yarp_ros_proxy_URL_WEBSITE "")
set(yarp_ros_proxy_URL_BUGTRACKER "")
set(yarp_ros_proxy_URL_REPOSITORY "")
set(yarp_ros_proxy_DEPRECATED "")