set(_CATKIN_CURRENT_PACKAGE "yarp")
set(yarp_VERSION "0.0.0")
set(yarp_MAINTAINER "jbarmagen <jbarmagen@todo.todo>")
set(yarp_PACKAGE_FORMAT "2")
set(yarp_BUILD_DEPENDS "roscpp" "rospy" "std_msgs" "message_generation")
set(yarp_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs")
set(yarp_BUILDTOOL_DEPENDS "catkin")
set(yarp_BUILDTOOL_EXPORT_DEPENDS )
set(yarp_EXEC_DEPENDS "roscpp" "rospy" "std_msgs" "message_runtime")
set(yarp_RUN_DEPENDS "roscpp" "rospy" "std_msgs" "message_runtime")
set(yarp_TEST_DEPENDS )
set(yarp_DOC_DEPENDS )
set(yarp_URL_WEBSITE "")
set(yarp_URL_BUGTRACKER "")
set(yarp_URL_REPOSITORY "")
set(yarp_DEPRECATED "")