set(_CATKIN_CURRENT_PACKAGE "yarp_ros_interfaces")
set(yarp_ros_interfaces_VERSION "0.0.0")
set(yarp_ros_interfaces_MAINTAINER "jbarmagen <jbarmagen@todo.todo>")
set(yarp_ros_interfaces_PACKAGE_FORMAT "2")
set(yarp_ros_interfaces_BUILD_DEPENDS "roscpp" "rospy" "std_msgs" "message_generation")
set(yarp_ros_interfaces_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs")
set(yarp_ros_interfaces_BUILDTOOL_DEPENDS "catkin")
set(yarp_ros_interfaces_BUILDTOOL_EXPORT_DEPENDS )
set(yarp_ros_interfaces_EXEC_DEPENDS "roscpp" "rospy" "std_msgs" "message_runtime")
set(yarp_ros_interfaces_RUN_DEPENDS "roscpp" "rospy" "std_msgs" "message_runtime")
set(yarp_ros_interfaces_TEST_DEPENDS )
set(yarp_ros_interfaces_DOC_DEPENDS )
set(yarp_ros_interfaces_URL_WEBSITE "")
set(yarp_ros_interfaces_URL_BUGTRACKER "")
set(yarp_ros_interfaces_URL_REPOSITORY "")
set(yarp_ros_interfaces_DEPRECATED "")